DROP TABLE IF EXISTS `gls0x12definitions`;					
SET @saved_cs_client     = @@character_set_client;					
SET character_set_client = utf8;					
CREATE TABLE `gls0x12definitions` (					
  `id` int(11) NOT NULL auto_increment,					
  `DefinitionID` varchar(100) NOT NULL,					
  `Description` varchar(1000) NOT NULL,					
  `DataType` varchar(100) ,					
  `Value` varchar(400) ,					
  `Example` varchar(200) ,					
  PRIMARY KEY  (`id`)					
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;					
SET character_set_client = @saved_cs_client;					
LOCK TABLES `gls0x12definitions` WRITE;					
INSERT INTO `gls0x12definitions` (`id`, `DefinitionID`, `Description`, `DataType`, `Value`, `Example` ) VALUES 					
(1,	'service',	'Service type identifier.',	'Character String',	'Must be "GLS"',	'GLS'),
(2,	'version',	'GLS specification and schema version.',	'Character String',	'Must be "0.12"',	'0.12'),
(3,	'xml:lang',	'Language of any human-readable text (e.g. "en-CA")',	'Character String',	'Language of any human-readable text (e.g. "en-CA")',	'en-CA'),
(4,	'xmlns',	'default XML namespace.',	'URL',	'Must be "http://www.opengis.net/gls/0.12".',	'http://www.opengis.net/gls/0.12'),
(5,	'xmlns:ows',	'OWS XML namespace',	'URL',	'Must be "http://www.opengis.net/ows/1.1"',	'http://www.opengis.net/ows/1.1'),
(6,	'xmlns:xsi',	'XML Schema namespace',	'URL',	'Must be "http://www.w3.org/2001/XMLSchema-instance"',	'http://www.w3.org/2001/XMLSchema-instance'),
(7,	'xsi:schemaLocation',	'location of the GLS Schema',	'URL',	'Must include "http://www.opengis.net/gls/0.12".  May include location of copy to be used.',	'http://www.opengis.net/gls/0.12  ../glsDescribeFrameworks_response.xsd'),
(8,	'ows:ServiceIdentification',	'Contains XML elements describing this service',	'XML elements',	'',	''),
(9,	'ows:ServiceProvider',	'Contains XML elements describing the service provider (owner).',	'XML elements',	'',	''),
(10,	'ows:OperationsMetadata',	'Contains XML elements describing the operations available at this service instance.',	'XML elements',	'',	''),
(11,	'ows:Operation',	'Contains XML elements describing an operation',	'XML elements',	'',	''),
(12,	'ows:Constraint',	'Contains XML elements describing a constraint',	'XML elements',	'',	''),
(13,	'ows:AllowedValues',	'Contains XML elements describing allowed values',	'XML elements',	'',	''),
(14,	'ows:Range',	'Contains XML elements describing a numeric range',	'XML elements',	'',	''),
(15,	'ows:MaximumValue',	'Maximum number of framework keys that can be included as part of a request.',	'Positive Integer',	'',	''),
(16,	'ows:Meaning',	'Human readable text description of the meaning of this constraint.',	'Character String',	'',	''),
(17,	'Languages',	'Contains list of languages fully supported by this service.',	'XML elements',	'',	''),
(18,	'ows:Language',	'Language of any human-readable text (e.g. "en-CA")',	'Character String',	'Language of any human-readable text (e.g. "en-CA")',	''),
(19,	'WSDL',	'Contains the URL of a WSDL document',	'XML elements',	'',	''),
(20,	'xlink:href',	'The URL of a WSDL document that describes the service.',	'URL',	'',	''),
(21,	'GDAS',	'Root element containing attribute data and all associated metadata ',	'XML elements',	'',	''),
(22,	'Framework',	'Contains XML elements that describe a spatial framework.',	'XML elements',	'',	''),
(23,	'FrameworkURI',	'A URI that uniquely references the spatial framework.  Normally a URL, but a URN may be used.',	'URI',	'',	''),
(24,	'Organization',	'The name of the organization that is responsible for maintaining the framework dataset. ',	'Character String',	'',	''),
(25,	'Title',	'A human readable sentence fragment that describes the object and may be used to form a title or to populate a picklist. ',	'Character String',	'',	''),
(26,	'Abstract',	'A complete human readable description of the object.',	'Character String',	'',	''),
(27,	'ReleaseDate',	'The date on which this object was first released for use.  ',	'Character String',	'',	''),
(28,	'Documentation',	'The URL of a web-accessible resource containing documentation describing this object.',	'URL',	'',	''),
(29,	'FrameworkKey',	'The key field within the framework dataset (i.e. in the GIS) that is referenced by all datasets that apply to this Framework.',	'Character String',	'',	''),
(30,	'BoundingBox',	'Identifies the bounding box of the spatial framework using the WGS84 CRS.',	'XML elements',	'',	''),
(31,	'Dataset',	'Contains XML elements that describe a dataset.  This dataset contains attribute information that applies to the spatial framework.',	'XML elements',	'',	''),
(32,	'Minimum',	'Contains XML elements that describe the minimum coordinates of the spatial framework.',	'XML elements',	'',	''),
(33,	'Maximum',	'Contains XML elements that describe the maximum coordinates of the spatial framework. ',	'XML elements',	'',	''),
(34,	'Latitude',	'Latitude coordinate in the WGS84 Coordinate Reference System.',	'Decimal',	'',	''),
(35,	'Longitude',	'Longitude coordinate in the WGS84 Coordinate Reference System.',	'Decimal',	'',	''),
(36,	'DatasetURI',	'A URI that uniquely identifies the attribute dataset.  Normally a URL, but a URN may be used.',	'URI',	'',	''),
(37,	'DatasetKey',	'The key field within the attribute dataset (i.e. the corporate database) that references the foreign key found in the spatial framework.  ',	'Character String',	'',	''),
(38,	'KeyRelationship',	'Identifies if the relationship between the Framework and the Attribute datasets are 1:1 or 1:many.  "one" indicates that there is at most one record in the Attribute dataset for every identifier in the Framework dataset.  "many" indicates that there may be more than one record in the Attribute dataset for every identifier in the Framework dataset.',	'Character String',	'Must be "one" or "many"',	''),
(39,	'KeyComplete',	'Identifies that there is at least one record in the Attribute dataset for every record in the Framework dataset.  "true" indicates that this is the case. "false" indicates that some identifiers in the Framework dataset cannot be found in the Attribute dataset.',	'Boolean',	'Must be "true" or "false"',	''),
(40,	'Attribute',	'Contains XML elements that describe a data field (i.e column of the dataset).',	'XML elements',	'',	''),
(41,	'type',	'Datatype, as defined by XML schema',	'URI type',	'',	'e.g. http://www.w3.org/TR/xmlschema-2/#integer'),
(42,	'length',	'Length of the field, in characters or digits',	'Positive Integer',	'',	''),
(43,	'decimals',	'Number of digits after the decimal, for decimal numbers with a fixed number of digits after the decimal.  ',	'Positive Integer',	'',	''),
(44,	'purpose',	'Purpose of the data field, indicating whether the attribute contains data, a linkage key, or other content.',	'Character String',	'',	''),
(45,	'AttributeName',	'The name of the data field.  Generally the name by which the attribute is identified within the RDBMS database.',	'Character String',	'',	''),
(46,	'Values',	'Description of the content of the attribute.',	'XML elements',	'',	''),
(47,	'Rowset',	'Attribute values',	'XML elements',	'',	''),
(48,	'Nominal/Ordinal/Measure/Count',	'Choice of Attribute type.  ',	'XML elements',	'',	''),
(49,	'Nominal',	'Contains XML elements that describe an attribute consisting of Nominal data (i.e. names, such as "Canada")',	'XML elements',	'',	''),
(50,	'Ordinal',	'Contains XML elements that describe an attribute consisting of Ordinal data (i.e. rankings, such as "high=1, medium=2, low=3"',	'XML elements',	'',	''),
(51,	'Count',	'Contains XML elements that describe an attribute consisting of Count data (i.e. total number of objects, such as "number of cows")',	'XML elements',	'',	''),
(52,	'Measure',	'Contains XML elements that describe an attribute consisting of Measure data (i.e. numeric measurement or calculated value such as "degrees Celsius")',	'XML elements',	'',	''),
(53,	'Classes',	'Contains XML elements that describe all valid classes for this attribute field.  This element is populated if the field contains classification information of some kind (e.g. geological classifications).',	'XML elements',	'',	''),
(54,	'Exceptions',	'Contains XML elements that describe all valid exception classes for this attribute field.',	'XML elements',	'',	''),
(55,	'Value',	'Contains XML elements that describe a valid (non-null) class that is present in this attribute field.',	'Character String',	'',	''),
(56,	'Identifier',	'Unique identifier within this group of objects.',	'Character String',	'',	''),
(57,	'Null',	'Contains XML elements that describe a valid exception class for this attribute field.',	'XML elements',	'',	''),
(58,	'rank',	'Ordinal ranking for this value',	'Non-negative Integer',	'',	''),
(59,	'UOM',	'Unit of Measure',	'Character String',	'',	''),
(60,	'Uncertainty',	'Contains XML elements that describe the standard measure of uncertainty (u<sub>i</sub>) equal to the positive square root of the estimated variance for this data.  See <a href="http://physics.nist.gov/cuu/Uncertainty/"/>',	'XML elements',	'',	''),
(61,	'reference',	'URL reference to an authoritative description.',	'URI',	'',	''),
(62,	'gaussian',	'Distribution form of the data.  When "true" the distribution of the data is Gaussian and Independent and Identically Distributed (IID)',	'Character String',	'true, "false", or "unknown".  Default is "unknown".',	''),
(63,	'Row',	'Contains XML elements that describe a data row which includes selected fields from the database.',	'XML elements',	'',	''),
(64,	'K',	'Key (e.g. polygon identifier) that references the spatial feature to which this row applies. Note that this identifier is a member of the DatasetKey   ',	'Character String',	'',	''),
(65,	'V',	'Value of a specified attribute for the spatial feature identified by the key for this Row.  When this value is null it must be indicated by setting the null attribute to "true".   An identification of the reason may be included in the content of this element, but it must be described in the Exceptions element.  ',	'XML elements',	'',	''),
(66,	'aid',	'Attribute identifier, namely the corresponding AttributeName',	'Character String',	'',	''),
(67,	'null',	'Boolean value, when present and "true" indicates that this particular value is missing for some reason, and the contents of the element must be processed accordingly.  ',	'Boolean',	'true, or "false".  Default is "false".',	''),
(68,	'updateSupported',	'Boolean that identifies if existing JoinData products can be updated by this service.  If "true" then subsequent identical JoinData requests will update existing JoinData products that were created by this service.  These updated products will then be available via the existing URLs of those products.',	'Boolean',	'true, or "false".  Default is "false".',	''),
(69,	'SpatialFrameworks',	'Full description of all spatial frameworks to which attribute data can be joined.',	'XML elements',	'',	''),
(70,	'AttributeLimit',	'Maximum number of attributes that can be joined simultaneously as part of a JoinData request.',	'Positive Integer',	'',	''),
(71,	'OutputMechanisms',	'List of mechanisms by which the attribute data will be accessible once it has been joined to the spatial framework.',	'XML elements',	'',	''),
(72,	'OutputStylings',	'Unordered list of display or content styling instructions supported by the server and that can be applied if the AccessMechanisms of the requested output includes WMS.  If WMS is not supported by the server then this element shall not be present.  If WMS is supported and this element is not present, a default styling will be applied to the WMS layer.',	'XML elements',	'',	''),
(73,	'Styling',	'Describes a form of styling instruction supported by this server.',	'XML elements',	'',	''),
(74,	'Schema',	'Reference to a definition of XML elements or types supported for this styling instruction (e.g., a URL which returns the XSD for SLD 1.0). This parameter shall be included when the styling instructions are XML encoded using an XML schema. When included, the input/output shall validate against the referenced XML Schema. This element shall be omitted if Schema does not apply to this form of styling instruction. <br/> Note: If this styling instruction uses a profile of a larger schema, the server administrator should provide that schema profile for validation purposes.',	'URI',	'',	''),
(75,	'ServiceInstance',	'The GetCapabilitiesURL of the GLS service which was invoked.',	'URL',	'',	''),
(76,	'StatusLocation',	'Reference to a location where the current JoinDataResponse document is stored.',	'URL',	'',	''),
(77,	'Status',	'Execution status of the JoinData request',	'XML elements',	'',	''),
(78,	'JoinedOutputs',	'List of outputs resulting from the JoinData operation.  There must be at least one output when the operation has completed successfully.',	'XML elements',	'',	''),
(79,	'creationTime',	'The time (UTC) that the JoinData operation finished.  If the operation is still in progress, this element shall contain the creation time of this document.',	'dateTime',	'',	''),
(80,	'Accepted|Completed|Failed',	'Choice of output status',	'XML elements',	'',	''),
(81,	'Accepted',	'Indicates that this request has been accepted by the server, but has not yet completed. ',	'Empty',	'',	''),
(82,	'Completed',	'Indicates that this request has completed execution with at lease partial success. ',	'Empty',	'',	''),
(83,	'Failed',	'Indicates that execution of the JoinData operation failed, and includes error information.',	'Character String',	'',	''),
(84,	'Output',	'Unordered list of all the outputs that have been or will be produced by this operation.',	'XML elements',	'',	''),
(85,	'Mechanism',	'Mechanism by which the joined attribute data is available ',	'XML elements',	'',	''),
(86,	'Reference|ows:ExceptionReport',	'Choice of output type',	'XML elements',	'',	''),
(87,	'Reference',	'Reference to a web-accessible resource that was created by the JoinData operation, in the form of a URL from which this resource can be electronically retrieved.',	'URL',	'',	''),
(88,	'ows:ExceptionReport',	'Unordered list of one or more errors encountered during the JoinData operation for this output.  These Exception elements shall be interpreted by clients as being independent of one another (not hierarchical).  This element is populated when the production of this output did not succeed.',	'XML elements',	'',	''),
(89,	'ows:Exception',	'Error encountered during processing that prevented successful production of this output.',	'XML elements',	'',	''),
(90,	'exceptionCode',	'A code representing the type of this exception, which shall be selected from a set of exceptionCode values specified for the specific service operation and server. ',	'',	'',	''),
(91,	'locator',	'When included, this locator shall indicate to the client where an exception was encountered in servicing the client\'s operation request. This locator should be included whenever meaningful information can be provided by the server. ',	'Character String',	'',	''),
(92,	'ows:ExceptionText',	'Ordered sequence of text strings that describe this specific exception or error. The contents of these strings are left open to definition by each server implementation. A server is strongly encouraged to include at least one ExceptionText value, to provide more information about the detected error than provided by the exceptionCode. When included, multiple ExceptionText values shall provide hierarchical information about one detected error, with the most significant information listed first. ',	'Character String',	'',	'');
UNLOCK TABLES;					
